---
- name: install epel
  yum:
    name:
      - epel-release

- name: install packages
  yum:
    name:
      - chrony
      - libselinux-python
      - vim
      - vim-enhanced
      - mc
      - screen
      - ccze
      - redhat-lsb-core
      - wget
      - yum-utils
      - htop
      - sudo
      - iftop
      - net-tools
      - elinks
      - lynx
      - bind-utils
      - deltarpm
      - lsof
      - tree
      - traceroute
      - tcpdump
      - nmap
      - unzip
      - lbzip2
      - fuse-sshfs
      - bash-completion
    state: latest

- name: edit bashrc, vimrc
  shell:
    echo "alias vi='vim'" >> /root/.bashrc && echo "colorscheme desert" >> /etc/vimrc

- name: set timezone
  timezone:
    name: "{{ TIMEZONE_OS }}"

- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive


- name: add mappings to /etc/hosts
  blockinfile:
    path: "{{ HOSTS_FILE }}"
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: "{{ HOST_NAME_ZOO1 }}", ip: "{{ HOST_IP_ZOO1 }}" }
    - { name: "{{ HOST_NAME_ZOO2 }}", ip: "{{ HOST_IP_ZOO2 }}" }
    - { name: "{{ HOST_NAME_ZOO3 }}", ip: "{{ HOST_IP_ZOO3 }}" }
    - { name: "{{ HOST_NAME_PG01 }}", ip: "{{ HOST_IP_PG01 }}" }
    - { name: "{{ HOST_NAME_PG02 }}", ip: "{{ HOST_IP_PG02 }}" }
    - { name: "{{ HOST_NAME_PG03 }}", ip: "{{ HOST_IP_PG03 }}" }
  tags:
    - update_hosts

- name: firewalld disable
  service:
    name: firewalld
    state: stopped
    enabled: no

